### PR TITLE
Add linter, fix linting issues

### PR DESCRIPTION
**Pull request by NPrescott**
addresses issue #4. Using the eslint google configuration at @dbuentello's suggestion

There are 15 errors outstanding, all related to generating mock
data. Ignoring them along with an error involving the rootRequire
function in global scope (eventually this will be factored out).

### CODE REVIEW

**Comment by dbuentello** [comment]
could you add instructions to README

**Comment by dbuentello** [comment]
FYI im getting a weird error similar to https://github.com/google/eslint-config-google/issues/8

``` sh
/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:361
            throw e;
            ^

Error: Cannot find module 'eslint-config-xo' from '/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules'
Referenced from: google
Referenced from: /Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/.eslintrc
    at Function.module.exports [as sync] (/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:416:38)
    at load (/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:435:24)
    at /Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:338:28)
    at load (/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:462:22)
    at /Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/Users/dbuentello/_repos/Github/NodejsHouston/sidenote-server/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:338:28)
```

oddly enough though, if I declare `eslint` in the package.json it goes away...any ideas?

**Comment by NPrescott** [comment]
I can't reproduce, do you have a global `eslint` package? Is it possible that is out of date? I think there were issues with shareable configs prior to 2.2.

**Comment by dbuentello** [comment]
nope, what version of node are you using?

``` sh
$ node -v
v4.2.4
```

**Comment by NPrescott** [comment]
I'm on `v5.0.0` but I switched to `v4.2.4` and still can't reproduce. I do however see this message on installation:

```
issue-4 ~/Projects/nodejs-houston/sidechat/sidenote-server $ npm install
npm WARN peerDependencies The peer dependency eslint@>=2 included from eslint-config-google will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint@>=2 included from eslint-config-xo will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

So I'll go ahead and fix the `package.json` as such.

**Comment by dbuentello** [comment]
works like charm. Thanks! +1

**Pull request merged**
